/**
 * scripts/run-demo-show.ts
 *
 * Demo newscast runner for the aFLR React Viewbox.
 *
 * This script seeds sample media assets into the `public/media/` folder (only if they
 * don’t already exist) and drives the viewbox via WebSocket messages. It sends
 * a sequence of updates that simulate a brief newscast: initial headline, a
 * series of stories with accompanying images and audio, a ticker update, an
 * emergency alert overlay, and a clean sign-off.
 *
 * Usage:
 *   pnpm add -D ws tsx
 *   pnpm tsx scripts/run-demo-show.ts --seed
 *
 * Options:
 *   --ws    ws://localhost:8088    (override WS URL)
 *   --seed                      seed demo assets
 *   --fast                      reduce wait times for quick testing
 *
 * Environment variables (overrides):
 *   WS_URL         override WebSocket URL
 *   SEED_ASSETS    set to '1' to seed assets
 *   FAST           set to '1' to enable fast mode
 */

import WebSocket from "ws";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

type WsEnvelope = {
  type: string;
  timestamp: number;
  data: Record<string, unknown>;
};

// Determine project root relative to this file
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..", "..");

// Parse CLI arguments
const argv = process.argv.slice(2);
const getArg = (name: string): string | undefined => {
  const idx = argv.indexOf(name);
  if (idx === -1) return undefined;
  return argv[idx + 1];
};
const hasFlag = (name: string): boolean => argv.includes(name);

const wsUrl =
  getArg("--ws") ||
  process.env.WS_URL ||
  "ws://localhost:8088";

const seed =
  hasFlag("--seed") ||
  process.env.SEED_ASSETS === "1";

const fast =
  hasFlag("--fast") ||
  process.env.FAST === "1";

// Adjust timings for fast mode
const speed = fast ? 0.35 : 1.0;

/** Pause execution for a given number of milliseconds (scaled by speed). */
const sleep = (ms: number) =>
  new Promise<void>((resolve) => setTimeout(resolve, ms * speed));

/** Check if a file exists. */
async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

/** Ensure a directory exists. */
async function ensureDir(dir: string): Promise<void> {
  await fs.mkdir(dir, { recursive: true });
}

/** Generate a demo headline SVG card. */
function svgCard(opts: { title: string; subtitle?: string; bg?: string }): string {
  const bg = opts.bg ?? "#111827";
  const subtitle = opts.subtitle ?? "";
  return `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">\n  <defs>\n    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">\n      <stop offset="0%" stop-color="${bg}" />\n      <stop offset="100%" stop-color="#000000" />\n    </linearGradient>\n  </defs>\n  <rect width="1280" height="720" fill="url(#g)" />\n  <rect x="40" y="40" width="1200" height="640" fill="rgba(0,0,0,0.35)" stroke="rgba(255,255,255,0.2)" />\n  <text x="80" y="160" fill="#ffffff" font-size="64" font-family="Arial, sans-serif" font-weight="700">${escapeXml(opts.title)}</text>\n  <text x="80" y="240" fill="#d1d5db" font-size="32" font-family="Arial, sans-serif">${escapeXml(subtitle)}</text>\n  <text x="80" y="660" fill="#9ca3af" font-size="22" font-family="Arial, sans-serif">Demo asset generated by run-demo-show.ts</text>\n</svg>`;
}

/** Escape special characters for SVG text nodes. */
function escapeXml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("\"", "&quot;")
    .replaceAll("'", "&apos;");
}

/** Generate a simple mono WAV tone buffer (16-bit PCM). */
function generateWavTone(opts: {
  durationSec: number;
  freqHz: number;
  sampleRate?: number;
  volume?: number; // 0..1
}): Buffer {
  const sampleRate = opts.sampleRate ?? 44100;
  const volume = Math.max(0, Math.min(1, opts.volume ?? 0.25));
  const numSamples = Math.floor(sampleRate * opts.durationSec);

  const bytesPerSample = 2; // 16-bit
  const dataSize = numSamples * bytesPerSample;
  const headerSize = 44;
  const fileSize = headerSize + dataSize;

  const buf = Buffer.alloc(fileSize);

  // RIFF header
  buf.write("RIFF", 0);
  buf.writeUInt32LE(fileSize - 8, 4);
  buf.write("WAVE", 8);

  // fmt chunk
  buf.write("fmt ", 12);
  buf.writeUInt32LE(16, 16); // PCM chunk size
  buf.writeUInt16LE(1, 20); // audio format = PCM
  buf.writeUInt16LE(1, 22); // num channels = 1
  buf.writeUInt32LE(sampleRate, 24);
  buf.writeUInt32LE(sampleRate * bytesPerSample, 28); // byte rate
  buf.writeUInt16LE(bytesPerSample, 32); // block align
  buf.writeUInt16LE(16, 34); // bits per sample

  // data chunk
  buf.write("data", 36);
  buf.writeUInt32LE(dataSize, 40);

  // generate sine wave samples
  const twoPiF = 2 * Math.PI * opts.freqHz;
  for (let i = 0; i < numSamples; i++) {
    const t = i / sampleRate;
    const s = Math.sin(twoPiF * t) * volume;
    const v = Math.round(s * 32767);
    buf.writeInt16LE(v, headerSize + i * 2);
  }

  return buf;
}

/** Create placeholder media files for the demo run if they don't already exist. */
async function seedDemoAssets(): Promise<void> {
  const base = path.join(repoRoot, "public", "media");

  const dirLayer1 = path.join(base, "layer1");
  const dirContent = path.join(base, "content");
  const dirAudio = path.join(base, "audio");
  const dirMarquee = path.join(base, "marquee");

  await ensureDir(dirLayer1);
  await ensureDir(dirContent);
  await ensureDir(dirAudio);
  await ensureDir(dirMarquee);

  // Generate SVG story cards (main content) if missing
  await writeIfMissing(
    path.join(dirContent, "demo_story1.svg"),
    svgCard({
      title: "BREAKING: Scanner Activity",
      subtitle: "Multiple units dispatched • Stand by",
      bg: "#4c1d95",
    })
  );

  await writeIfMissing(
    path.join(dirContent, "demo_story2.svg"),
    svgCard({
      title: "TRAFFIC: Slowdowns Reported",
      subtitle: "Route 11 congestion near downtown",
      bg: "#1f2937",
    })
  );

  await writeIfMissing(
    path.join(dirContent, "demo_story3.svg"),
    svgCard({
      title: "COURTS: Daily Schedule",
      subtitle: "Arraignments begin 9:00 AM",
      bg: "#0f172a",
    })
  );

  // Generate WAV audio files (background bed and narration clips)
  await writeIfMissing(
    path.join(dirLayer1, "demo_bed.wav"),
    generateWavTone({ durationSec: 6.0, freqHz: 110, volume: 0.12 })
  );

  await writeIfMissing(
    path.join(dirAudio, "demo_story1.wav"),
    generateWavTone({ durationSec: 4.0, freqHz: 440, volume: 0.25 })
  );

  await writeIfMissing(
    path.join(dirAudio, "demo_story2.wav"),
    generateWavTone({ durationSec: 4.0, freqHz: 523.25, volume: 0.25 })
  );

  await writeIfMissing(
    path.join(dirAudio, "demo_story3.wav"),
    generateWavTone({ durationSec: 4.0, freqHz: 659.25, volume: 0.25 })
  );

  // Create marquee text files with color codes
  await writeIfMissing(
    path.join(dirMarquee, "DEMO_TOP_3366FF.txt"),
    [
      "BREAKING: Scanner reports increased activity • Updates pending",
      "TRAFFIC: Slowdowns near downtown • Use alternate routes",
      "COURTS: Arraignments scheduled 9:00 AM • Public docket posted",
      "WEATHER: Cold front moving in overnight • Stay alert",
    ].join("\n")
  );

  await writeIfMissing(
    path.join(dirMarquee, "DEMO_ALERT_FF0000.txt"),
    [
      "EMERGENCY: Severe Weather Warning • Seek shelter if necessary",
      "PUBLIC SAFETY: Avoid restricted areas • Follow official guidance",
      "UPDATES: More details as confirmed • Stand by",
    ].join("\n")
  );

  console.log("✅ Seeded demo assets into public/media/** (if missing)");
}

/** Write file only if it does not exist. */
async function writeIfMissing(filePath: string, contents: string | Buffer): Promise<void> {
  const exists = await fileExists(filePath);
  if (exists) return;
  await fs.writeFile(filePath, contents);
}

/** Generate a timestamp in milliseconds. */
function nowMs(): number {
  return Date.now();
}

/** Construct a WebSocket envelope with current timestamp. */
function makeMsg(type: string, data: Record<string, unknown>): WsEnvelope {
  return { type, timestamp: nowMs(), data };
}

/** Main function to run the demo show. */
async function runDemo(): Promise<void> {
  if (seed) {
    await seedDemoAssets();
  }

  console.log(`🎛️  Demo show connecting to WS: ${wsUrl}`);
  const ws = new WebSocket(wsUrl);

  // Helper: send a typed message via WS
  const send = async (type: string, data: Record<string, unknown>): Promise<void> => {
    const msg = makeMsg(type, data);
    const raw = JSON.stringify(msg);
    await new Promise<void>((resolve, reject) => {
      ws.send(raw, (err) => (err ? reject(err) : resolve()));
    });
    console.log(`→ sent ${type}`, data);
  };

  // Wait for socket open
  await new Promise<void>((resolve, reject) => {
    ws.on("open", () => resolve());
    ws.on("error", (e) => reject(e));
  });

  // If the relay echoes messages, log them for visibility
  ws.on("message", (data) => {
    console.log(`← recv ${(data.toString() as string).slice(0, 200)}...`);
  });

  // === Begin show sequence ===

  // 0) Baseline: temperature and ticker
  await send("weatherUpdate", { temperature: 34 });
  await send("marqueeUpdate", { marqueefile: "DEMO_TOP_3366FF.txt" });

  // Optional: ambient bed
  await send("backgroundaudioUpdate", { audioSrc: "demo_bed.wav" });

  // 1) Open: station ID / headline
  await send("headlineUpdate", { headline: "ASHTABULA FRONTLINE REPORT" });
  await send("subtextUpdate", { subtext: "AUTONOMOUS LOCAL NEWS • LIVE DEMO SEQUENCE" });
  await sleep(1200);

  // 2) Story 1: Breaking scanner activity
  await send("fullStoryUpdate", {
    headline: "BREAKING: Scanner Activity",
    subtext: "Multiple units dispatched • Stand by",
    mediatype: 1,
    materials: "demo_story1.svg",
  });
  await sleep(300);
  await send("mainaudioUpdate", {
    command: "play_clip",
    filename: "demo_story1.wav",
    seqlength: 1,
  });
  await sleep(4200);

  // 3) Story 2: Traffic
  await send("fullStoryUpdate", {
    headline: "TRAFFIC: Slowdowns Reported",
    subtext: "Route 11 congestion near downtown",
    mediatype: 1,
    materials: "demo_story2.svg",
  });
  await sleep(300);
  await send("mainaudioUpdate", {
    command: "play_clip",
    filename: "demo_story2.wav",
    seqlength: 1,
  });
  await sleep(4200);

  // 4) Update ticker to alert mode
  await send("marqueeUpdate", { marqueefile: "DEMO_ALERT_FF0000.txt" });
  await sleep(800);

  // 5) Emergency alert overlay
  await send("emergencyAlert", {
    alertcontent: "SEVERE WEATHER WARNING: Seek shelter immediately if instructed by authorities.",
  });
  await sleep(2200);
  // Hide overlay after short delay
  await send("hideLayer5", { stalltime: 900 });
  await sleep(1200);

  // 6) Story 3: Courts
  await send("fullStoryUpdate", {
    headline: "COURTS: Daily Schedule",
    subtext: "Arraignments begin 9:00 AM",
    mediatype: 1,
    materials: "demo_story3.svg",
  });
  await sleep(300);
  await send("mainaudioUpdate", {
    command: "play_clip",
    filename: "demo_story3.wav",
    seqlength: 1,
  });
  await sleep(4200);

  // 7) Wrap up the demo
  await send("headlineUpdate", { headline: "END OF DEMO" });
  await send("subtextUpdate", { subtext: "If you saw smooth updates, the protocol contract is working ✅" });
  await sleep(1200);
  await send("mainaudioUpdate", { command: "stop", filename: null, seqlength: 1 });
  await send("backgroundaudioUpdate", { audioSrc: null });

  console.log("✅ Demo show complete. Closing WS.");
  ws.close();
}

runDemo().catch((err) => {
  console.error("❌ Demo show failed:", err);
  process.exitCode = 1;
});